name: dask-pycon
dependencies:
 - dask
 - dask-ml
 - distributed
 - gcsfs
 - graphviz
 - h5py
 - ipywidgets
 - jupyter
 - jupyterlab
 - matplotlib
 - memory_profiler
 - numba
 - numpy
 - pandas
 - pillow
 - pytables
 - python=3
 - s3fs
 - scikit-learn
 - scipy
 - snakeviz=0.4.0
 - pip:
   - graphviz
   - cachey
